name: Node CI Pipeline

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Start App Test
        run: node src/app.js & sleep 5

      - name: Build Docker Image
        run: docker build -t node-demo:latest .
